// <auto-generated />
using System;
using BackendHorus.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendHorus.Migrations
{
    [DbContext(typeof(MicrorutasDbContext))]
    partial class MicrorutasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendHorus.Models.Incident", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("BackendHorus.Models.Macroruta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Macrorutas");
                });

            modelBuilder.Entity("BackendHorus.Models.Microruta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MacrorutaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PolylineJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("[]");

                    b.HasKey("Id");

                    b.HasIndex("MacrorutaId");

                    b.ToTable("Microrutas");
                });

            modelBuilder.Entity("BackendHorus.Models.PositionSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("TripId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TripId");

                    b.ToTable("PositionSamples");
                });

            modelBuilder.Entity("BackendHorus.Models.Recolector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.ToTable("Recolectores");
                });

            modelBuilder.Entity("BackendHorus.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Bolsas")
                        .HasColumnType("int");

                    b.Property<double>("CoberturaPorciento")
                        .HasColumnType("float");

                    b.Property<double>("DistanciaMetros")
                        .HasColumnType("float");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("MicrorutaId")
                        .HasColumnType("int");

                    b.Property<int>("RecolectorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MicrorutaId");

                    b.HasIndex("RecolectorId");

                    b.ToTable("Trips");
                });

            modelBuilder.Entity("BackendHorus.Models.Incident", b =>
                {
                    b.HasOne("BackendHorus.Models.Trip", "Trip")
                        .WithMany("Incidents")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("BackendHorus.Models.Microruta", b =>
                {
                    b.HasOne("BackendHorus.Models.Macroruta", "Macroruta")
                        .WithMany("Microrutas")
                        .HasForeignKey("MacrorutaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Macroruta");
                });

            modelBuilder.Entity("BackendHorus.Models.PositionSample", b =>
                {
                    b.HasOne("BackendHorus.Models.Trip", "Trip")
                        .WithMany("Positions")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("BackendHorus.Models.Trip", b =>
                {
                    b.HasOne("BackendHorus.Models.Microruta", "Microruta")
                        .WithMany("Trips")
                        .HasForeignKey("MicrorutaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendHorus.Models.Recolector", "Recolector")
                        .WithMany("Trips")
                        .HasForeignKey("RecolectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Microruta");

                    b.Navigation("Recolector");
                });

            modelBuilder.Entity("BackendHorus.Models.Macroruta", b =>
                {
                    b.Navigation("Microrutas");
                });

            modelBuilder.Entity("BackendHorus.Models.Microruta", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("BackendHorus.Models.Recolector", b =>
                {
                    b.Navigation("Trips");
                });

            modelBuilder.Entity("BackendHorus.Models.Trip", b =>
                {
                    b.Navigation("Incidents");

                    b.Navigation("Positions");
                });
#pragma warning restore 612, 618
        }
    }
}
